### ISSUE TITLE
Domanda sul grafico

### ISSUE THREAD

**Issue by Marco-Saini** [DavideBrambilla98/ProgettoPW2024#3]
![image](https://github.com/DavideBrambilla98/ProgettoPW2024/assets/145766844/0f43a036-e2fa-4769-bff8-a8b534fb321f)
scusate la domanda stupida ma la cardinalitá é corretta, cioé é giusto che un ricovero abbia (0,n) ospedali e ospedali abbia (1,1) ricovero? o sto invertendo il modo di leggere il garfico?

**Comment by MarcoAlgisi** [comment]
stai invertendo. ricovero è relativo a uno e un solo osp, mentre lui può avere più ricoveri

**Comment by Marco-Saini** [comment]
ok grazie perfetto grazie
