### ISSUE TITLE
Tabella PatologiaRicovero

### ISSUE THREAD

**Issue by DavideBrambilla98** [DavideBrambilla98/ProgettoPW2024#6]
Bisogna decidere come far vedere la tabella che mette insieme le patologie con i ricoveri

- Nella tabella patologia, aggiungere una colonna che mostra il numero di ricoveri con quella patologia
- Nella tabella ricoveri aggiungere anche la colonna codice patologia per poterle mettere in relazione

**Comment by Marco-Saini** [comment]
cosa avevi in mente?
Off topic meet di domenica?

**Comment by DavideBrambilla98** [comment]
Si va bene per Meet, così vediamo cosa fare

**Comment by DavideBrambilla98** [comment]
Soluzione: creare tabella PatologieRicoveri per poi essere usata nelle varie query SQL
(La tabella PatologieRicoveri non verrà visualizzata come pagina nel sito)
